/' Ingeniería de Software UCV - 2023
Práctica 02 - Ejercicio 3.b.1
Rahi-Mon '/

@startuml Class Diagram
title Diagrama de Clases - 3.b.1

class Teclado{}
class Tecla{}

Teclado "1" *-- "105..*" Tecla : tiene

@enduml