@startuml
title Diagrama de Secuencias - Ejercicio (a1)

/' Initiator-Trigger is actually UNKNOWN 
in (miLista.getItem()).hacerAlgo().
Iniciador desconocido.'/

/' Previous errors --> Uncertainty of Initiator.
 Insightful understanding via Answer keys document'/

participant "?" as Unknown
participant "miLista : Lista" as M
participant "item : Item" as I


Unknown -> M : 1: getItem()
activate Unknown
activate M
M -->> Unknown : 1.1: item 
deactivate M 

Unknown -> I : 2: hacerAlgo()
activate I
deactivate M 
deactivate I
deactivate Unknown 


@enduml